'use strict';

const { execFile } = require('child_process');
const fs   = require('fs');
const path = require('path');
const os   = require('os');
const { v4: uuidv4 } = require('uuid');
const config = require('../config/default.json');
const logger = require('../logger');

// ---------------------------------------------------------------------------
// Script templates — one per insight category
// ---------------------------------------------------------------------------

function buildScript(insight) {
  const title    = insight.title || 'Unknown Issue';
  const comps    = (insight.affectedComponents || []).join(', ') || 'system';
  const category = insight.category || 'performance';

  const scripts = {
    hardware: `#!/bin/bash
# Remediation: ${title}
# Category: hardware | Risk: LOW | Estimated: ~30s
# Generated by Edge AI Intelligence Engine
# Requires approval before execution.

set -euo pipefail

echo "[INFO] Starting thermal remediation for ${comps}..."

# Step 1: Adjust fan curve to aggressive profile
echo "[INFO] Setting fan profile to aggressive..."
if [ -f /sys/class/npu/fan_profile ]; then
  echo "aggressive" > /sys/class/npu/fan_profile
else
  echo "[WARN] NPU fan_profile sysfs not found – skipping fan step."
fi

# Step 2: Reduce NPU frequency cap to manage thermals
echo "[INFO] Attempting to cap NPU frequency to 1800MHz..."
if [ -f /sys/class/npu/freq_cap ]; then
  echo 1800000 > /sys/class/npu/freq_cap
else
  echo "[WARN] NPU freq_cap sysfs not found – skipping frequency step."
fi

# Step 3: Verify current temperature
sleep 3
TEMP_RAW=\$(cat /sys/class/thermal/thermal_zone0/temp 2>/dev/null || echo "0")
TEMP=\$(echo "scale=1; \${TEMP_RAW}/1000" | bc 2>/dev/null || echo "N/A")
echo "[INFO] Current temperature: \${TEMP}°C"

echo "[DONE] Thermal remediation script completed."
`,

    software: `#!/bin/bash
# Remediation: ${title}
# Category: software | Risk: MEDIUM | Estimated: ~15s
# Generated by Edge AI Intelligence Engine
# Requires approval before execution.

set -euo pipefail

echo "[INFO] Initiating software remediation for ${comps}..."

# Step 1: Capture current memory state for diagnostics
echo "[INFO] Capturing memory snapshot..."
mkdir -p /var/log/edge-ai/remediation
free -h > /var/log/edge-ai/remediation/mem_snapshot_\$(date +%s).log 2>/dev/null || true

# Step 2: Clear PageCache, dentries and inodes (safe, no data loss)
echo "[INFO] Dropping filesystem caches (safe operation)..."
sync
echo 3 > /proc/sys/vm/drop_caches 2>/dev/null || echo "[WARN] drop_caches requires root – skipping."

# Step 3: Look for high-memory processes and log them
echo "[INFO] Top memory-consuming processes:"
ps aux --sort=-%mem | head -10 2>/dev/null || true

# Step 4: If a specific affected component is a systemd service, restart gracefully
COMPONENT="${comps}"
if systemctl is-active --quiet "\${COMPONENT}" 2>/dev/null; then
  echo "[INFO] Sending SIGTERM to \${COMPONENT} for graceful restart..."
  systemctl restart "\${COMPONENT}"
  sleep 2
  if systemctl is-active --quiet "\${COMPONENT}"; then
    echo "[SUCCESS] \${COMPONENT} restarted successfully."
  else
    echo "[ERROR] \${COMPONENT} failed to restart."
    exit 1
  fi
else
  echo "[INFO] No systemd service named \${COMPONENT} found – skipping service restart."
fi

echo "[DONE] Software remediation script completed."
`,

    security: `#!/bin/bash
# Remediation: ${title}
# Category: security | Risk: HIGH | Estimated: ~45s
# Generated by Edge AI Intelligence Engine
# WARNING: This script modifies firewall rules and may affect connectivity.
# Requires explicit approval before execution.

set -euo pipefail

echo "[WARN] SECURITY REMEDIATION — modifying system security settings."
echo "[INFO] Affected components: ${comps}"

# Step 1: Log current network connections for audit
echo "[INFO] Capturing active network connections..."
mkdir -p /var/log/edge-ai/remediation
ss -tupn > /var/log/edge-ai/remediation/connections_\$(date +%s).log 2>/dev/null || \
  netstat -tupn > /var/log/edge-ai/remediation/connections_\$(date +%s).log 2>/dev/null || true

# Step 2: Check for suspicious outbound connections (known bad ranges)
echo "[INFO] Checking for anomalous outbound traffic..."
if ss -tn 2>/dev/null | grep -E ':4444|:5555|:6666|:1234' | grep ESTABLISHED; then
  echo "[WARN] Suspicious outbound connection(s) detected."
fi

# Step 3: Drop and re-apply basic iptables OUTPUT rules (non-destructive)
echo "[INFO] Reviewing iptables OUTPUT chain..."
iptables -L OUTPUT --line-numbers 2>/dev/null | head -20 || echo "[WARN] iptables not available."

# Step 4: Clear ARP cache (helps with ARP spoofing scenarios)
echo "[INFO] Flushing ARP cache..."
ip neigh flush all 2>/dev/null || arp -d -a 2>/dev/null || true

# Step 5: Kill any processes with suspicious CPU usage
echo "[INFO] Checking for high-CPU anomaly processes (>80%)..."
ps aux --sort=-%cpu | awk 'NR>1 && $3>80 {print $2, $11}' | while read pid cmd; do
  echo "[WARN] High-CPU process: PID=\${pid} CMD=\${cmd}"
  # We log but do NOT auto-kill – requires additional approval
done

# Step 6: Rotate application credentials (placeholder – adapt to your secret store)
echo "[INFO] Credential rotation: update application secrets as needed."
echo "[ACTION REQUIRED] Manually rotate API keys and database credentials."

echo "[DONE] Security remediation script completed. Review audit log at /var/log/edge-ai/remediation/"
`,

    performance: `#!/bin/bash
# Remediation: ${title}
# Category: performance | Risk: LOW | Estimated: ~20s
# Generated by Edge AI Intelligence Engine
# Requires approval before execution.

set -euo pipefail

echo "[INFO] Starting performance optimization for ${comps}..."

# Step 1: Adjust CPU governor to performance mode
echo "[INFO] Setting CPU governor to performance..."
for gov in /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor; do
  if [ -f "\${gov}" ]; then
    echo performance > "\${gov}" 2>/dev/null || true
  fi
done

# Step 2: Tune kernel scheduler for throughput
echo "[INFO] Tuning scheduler: sched_migration_cost..."
sysctl -w kernel.sched_migration_cost_ns=5000000 2>/dev/null || true

# Step 3: Drop filesystem caches to reclaim memory for application
echo "[INFO] Reclaiming filesystem cache memory..."
sync && echo 1 > /proc/sys/vm/drop_caches 2>/dev/null || true

# Step 4: Check top CPU-consuming processes
echo "[INFO] Current top CPU consumers:"
ps aux --sort=-%cpu | head -10 2>/dev/null || true

# Step 5: Verify improvement
sleep 3
LOAD=\$(cat /proc/loadavg | awk '{print \$1}')
echo "[INFO] 1-minute load average after optimization: \${LOAD}"

echo "[DONE] Performance optimization complete."
`,

    network: `#!/bin/bash
# Remediation: ${title}
# Category: network | Risk: LOW | Estimated: ~10s
# Generated by Edge AI Intelligence Engine
# Requires approval before execution.

set -euo pipefail

echo "[INFO] Starting network remediation for ${comps}..."

# Step 1: Show current interface statistics
echo "[INFO] Network interface statistics:"
ip -s link 2>/dev/null || ifconfig 2>/dev/null || true

# Step 2: Flush routing cache
echo "[INFO] Flushing routing cache..."
ip route flush cache 2>/dev/null || route -f 2>/dev/null || true

# Step 3: Check for dropped packets
echo "[INFO] Checking for packet drops..."
netstat -s 2>/dev/null | grep -i 'drop\|error\|fail' | head -10 || true

# Step 4: Restart network-manager if available
if systemctl is-active --quiet NetworkManager 2>/dev/null; then
  echo "[INFO] Restarting NetworkManager..."
  systemctl restart NetworkManager
  sleep 2
  echo "[INFO] NetworkManager restarted."
else
  echo "[INFO] NetworkManager not active – skipping restart."
fi

# Step 5: DNS flush
echo "[INFO] Flushing DNS cache..."
systemd-resolve --flush-caches 2>/dev/null || \
  resolvectl flush-caches 2>/dev/null || true

echo "[DONE] Network remediation complete."
`,
  };

  return scripts[category] || scripts.performance;
}

function buildSteps(category) {
  const stepsMap = {
    hardware:    ['Check thermal state', 'Adjust fan profile', 'Cap NPU frequency', 'Verify temperature'],
    software:    ['Snapshot memory', 'Drop filesystem caches', 'Identify top processes', 'Restart affected service', 'Verify recovery'],
    security:    ['Capture network audit', 'Check suspicious connections', 'Review firewall rules', 'Flush ARP cache', 'Scan for high-CPU anomalies', 'Credential rotation reminder'],
    performance: ['Set CPU governor', 'Tune scheduler', 'Reclaim cache', 'Verify load average'],
    network:     ['Show interface stats', 'Flush routing cache', 'Check packet drops', 'Restart NetworkManager', 'Flush DNS cache'],
  };
  return stepsMap[category] || stepsMap.performance;
}

function riskLevel(category, severity) {
  if (category === 'security') return 'high';
  if (severity === 'critical') return 'high';
  if (severity === 'high' || category === 'software') return 'medium';
  return 'low';
}

function estimatedDuration(category) {
  const durations = { hardware: '~30s', software: '~15s', security: '~45s', performance: '~20s', network: '~10s' };
  return durations[category] || '~20s';
}

// ---------------------------------------------------------------------------
// Service class
// ---------------------------------------------------------------------------

class RemediationService {
  constructor() {
    /** @type {Map<string, {plan: object, expiresAt: number}>} */
    this.plans = new Map();
  }

  /**
   * Generate a remediation plan for the given AI insight.
   * @param {object} insight - AiInsight object
   * @returns {object} RemediationPlan
   */
  generatePlan(insight) {
    const planId  = uuidv4();
    const script  = buildScript(insight);
    const category = insight.category || 'performance';
    const severity = insight.severity || 'low';

    const plan = {
      id:                planId,
      insightId:         insight.id,
      script,
      description:       `Auto-generated remediation for: ${insight.title}`,
      riskLevel:         riskLevel(category, severity),
      estimatedDuration: estimatedDuration(category),
      steps:             buildSteps(category),
      createdAt:         Date.now(),
    };

    const expiresAt = Date.now() + config.remediation.planExpiryMs;
    this.plans.set(planId, { plan, expiresAt });

    // Auto-expire
    setTimeout(() => this.plans.delete(planId), config.remediation.planExpiryMs);

    logger.info(`Remediation plan generated: ${planId} (${category}, ${severity})`);
    return plan;
  }

  /**
   * Execute a stored plan — ONLY if approved === true.
   * Scripts run via execFile with a temp file (no shell injection surface).
   * @param {string} planId
   * @param {boolean} approved
   * @returns {Promise<{success:boolean, message:string, output?:string}>}
   */
  async executePlan(planId, approved) {
    if (!approved) {
      logger.warn(`Remediation execution REJECTED by user for plan ${planId}`);
      return { success: false, message: 'Execution not approved by user.' };
    }

    const entry = this.plans.get(planId);
    if (!entry) {
      return { success: false, message: 'Plan not found or has expired (>5 min).' };
    }
    if (Date.now() > entry.expiresAt) {
      this.plans.delete(planId);
      return { success: false, message: 'Plan has expired. Generate a new remediation plan.' };
    }

    const { plan } = entry;
    const tmpFile  = path.join(os.tmpdir(), `edge-ai-remediation-${planId}.sh`);

    try {
      fs.writeFileSync(tmpFile, plan.script, { mode: 0o700 });
      logger.info(`Executing approved remediation plan ${planId} via ${tmpFile}`);

      return await new Promise((resolve) => {
        execFile('/bin/bash', [tmpFile], { timeout: 60_000 }, (error, stdout, stderr) => {
          try { fs.unlinkSync(tmpFile); } catch (_) {}

          if (error) {
            logger.error(`Remediation ${planId} failed: ${error.message}\n${stderr}`);
            resolve({ success: false, message: `Execution failed: ${error.message}`, output: stderr });
          } else {
            logger.info(`Remediation ${planId} succeeded:\n${stdout}`);
            this.plans.delete(planId); // consumed
            resolve({ success: true, message: 'Remediation executed successfully.', output: stdout });
          }
        });
      });
    } catch (err) {
      try { fs.unlinkSync(tmpFile); } catch (_) {}
      return { success: false, message: `Failed to write/execute script: ${err.message}` };
    }
  }

  /** Return all pending (non-expired) plan IDs */
  listPlans() {
    const now = Date.now();
    return [...this.plans.entries()]
      .filter(([, v]) => now < v.expiresAt)
      .map(([id, v]) => ({ id, insightId: v.plan.insightId, expiresAt: v.expiresAt }));
  }
}

const remediationService = new RemediationService();
module.exports = remediationService;
